-- MySQL Script generated by MySQL Workbench
-- Tue Jan 24 11:31:14 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema bgirl
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bgirl
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bgirl` DEFAULT CHARACTER SET utf8 ;
USE `bgirl` ;

-- -----------------------------------------------------
-- Table `bgirl`.`user`
-- -----------------------------------------------------

DROP TABLE IF EXISTS `user`;

CREATE TABLE IF NOT EXISTS `bgirl`.`user` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `phone` VARCHAR(20) NOT NULL COMMENT '手机号码',
  `passwd` VARCHAR(45) NOT NULL COMMENT '密码md5',
  `ucode` VARCHAR(45) NOT NULL COMMENT 'ucode',
  `nick` VARCHAR(45) NULL COMMENT '昵称',
  `realname` VARCHAR(45) NULL COMMENT '真实姓名',
  `birthday` DATETIME NULL COMMENT '出生日期',
  `score` INT NOT NULL DEFAULT 0 COMMENT '积分账户',
  `balance` INT NOT NULL DEFAULT 0 COMMENT '金币账户（备用）',
  `vipend` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'VIP到期时间',
  `status` TINYINT NOT NULL DEFAULT 1 COMMENT '状态,0-无效，1-有效',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `modify_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '用户表';


-- -----------------------------------------------------
-- Table `bgirl`.`pic`
-- -----------------------------------------------------


DROP TABLE IF EXISTS `pic`;

CREATE TABLE IF NOT EXISTS `bgirl`.`pic` (
  `id` INT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NULL COMMENT '文字说明',
  `min` VARCHAR(200) NOT NULL COMMENT '图片地址(小)',
  `normal` VARCHAR(200) NOT NULL COMMENT '图片地址(中)',
  `max` VARCHAR(200) NOT NULL COMMENT '图片地址(大)',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `modify_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '图片表';


-- -----------------------------------------------------
-- Table `bgirl`.`group`
-- -----------------------------------------------------

DROP TABLE IF EXISTS `group`;

CREATE TABLE IF NOT EXISTS `bgirl`.`group` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL COMMENT '名称',
  `des` TEXT NULL COMMENT '说明',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `modify_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '图片分组';


-- -----------------------------------------------------
-- Table `bgirl`.`group_pic_mapping`
-- -----------------------------------------------------

DROP TABLE IF EXISTS `group_pic_mapping`;

CREATE TABLE IF NOT EXISTS `bgirl`.`group_pic_mapping` (
  `id` INT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `pic_id` INT(20) NOT NULL COMMENT '图片id',
  `group_id` INT NOT NULL COMMENT '分组id',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `modify_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '图片分组映射表';


-- -----------------------------------------------------
-- Table `bgirl`.`channel`
-- -----------------------------------------------------

DROP TABLE IF EXISTS `channel`;

CREATE TABLE IF NOT EXISTS `bgirl`.`channel` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL COMMENT '频道表',
  `des` TEXT NULL,
  `create_time` DATETIME NOT NULL,
  `modify_time` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '频道表';


-- -----------------------------------------------------
-- Table `bgirl`.`group_channel_mapping`
-- -----------------------------------------------------

DROP TABLE IF EXISTS `group_channel_mapping`;

CREATE TABLE IF NOT EXISTS `bgirl`.`group_channel_mapping` (
  `id` INT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `channel_id` INT NOT NULL COMMENT '频道id',
  `group_id` INT NOT NULL COMMENT '分组id',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `modify_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '频道图组映射表';


DROP TABLE IF EXISTS `transaction`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `transaction` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `modify_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
  `create_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `user_id` int(11) DEFAULT NULL COMMENT '用户ID',
  `amount` int(11) DEFAULT NULL COMMENT '交易金额，单位为分',
  `pay_type` varchar(32) DEFAULT NULL COMMENT '交易类型，比如支付宝',
  `object_type` varchar(32) NOT NULL COMMENT '交易对象类型',
  `object_id` int(11) NOT NULL COMMENT '交易对象ID，比如充值订单ID',
  `status` varchar(32) NOT NULL COMMENT '状态',
  `memo` text COMMENT '备注',
  `pay_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '支付时间',
  `out_serial_no` varchar(128) DEFAULT NULL COMMENT '外部系统交易号',
  `title` varchar(128) DEFAULT NULL COMMENT '订单标题',
  `callback` varchar(512) DEFAULT NULL COMMENT '回调地址',
  `detail` varchar(1024) DEFAULT NULL COMMENT '订单详情',
  `payment_account` varchar(128) DEFAULT NULL COMMENT '支付帐号',
  `ip` varchar(32) DEFAULT NULL,
  `origin_object_id` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `user_id` (`user_id`),
  KEY `object_type_id` (`object_type`,`object_id`),
  KEY `origin_object_id` (`origin_object_id`),
  KEY `object_id` (`object_id`),
  KEY `pay_type` (`pay_type`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


--
-- Table structure for table `charge`
--

DROP TABLE IF EXISTS `charge`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `charge` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `user_id` int(11) DEFAULT NULL COMMENT '用户id，可以为空',
  `phone` varchar(16) DEFAULT NULL COMMENT '用户手机号码，可以为空',
  `amount` int(11) DEFAULT NULL COMMENT '金额，单位为分',
  `status` int(11) DEFAULT '1' COMMENT '状态，1 新建，2 完成，3 取消',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `modify_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `ip` varchar(32) DEFAULT NULL,
  `score` int(11) DEFAULT NULL COMMENT '充值赠送积分',
  `paid` int(11) DEFAULT NULL COMMENT '实际需要支付金额，单位为分',
  `category` int(11) DEFAULT '1' COMMENT '充值类型，用户，系统',
  `source` int(11) DEFAULT NULL,
  `pay_by` int(11) DEFAULT NULL,
  `ask_for` int(11) DEFAULT NULL COMMENT '充值邀请用户',
  `memo` varchar(200) DEFAULT NULL COMMENT '备注',
  `ask_for_status` int(11) DEFAULT NULL COMMENT '邀请充值状态',
  `discount_info` varchar(200) DEFAULT NULL COMMENT '充值折扣活动',
  `day` int(5) DEFAULT NULL,
  `discount_id` int(5) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_charge_user_id` (`user_id`),
  KEY `idx_charge_pay_by` (`pay_by`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;



--
-- Table structure for table `page_module`
--
DROP TABLE IF EXISTS `page_module`;
CREATE TABLE `page_module` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `page` varchar(20) NOT NULL COMMENT '页面名称',
  `category` varchar(20) NOT NULL DEFAULT 1 COMMENT '类型',
  `text` varchar(50) NULL COMMENT '标题文本',
  `icon` varchar(200) NULL COMMENT '标题图标',
  `des` varchar(500) NULL COMMENT '媒体简介',
  `style` text NULL COMMENT '样式扩展',
  `extend` text NULL COMMENT '扩展内容',
  `rank` int NOT NULL DEFAULT 0 COMMENT '排序字段',
  `status` tinyint NOT NULL DEFAULT 0 COMMENT '状态，0-可用，1-不可用',
  `createtime` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `modifytime` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后更新时间',
  `createby` varchar(50) NULL COMMENT '创建者',
  `modifyby` varchar(50) NULL COMMENT '最后更新者',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Table structure for table `page_content`
--
DROP TABLE IF EXISTS `page_content`;
CREATE TABLE `page_content` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `module_id` int(11) NOT NULL COMMENT '页面组件id',
  `category` int NOT NULL COMMENT '类型,0-专辑,1-频道',
  `pic_id` int(11) NOT NULL COMMENT '图片id',
  `component_id` int(11) NOT NULL COMMENT '组件id',
  `des` VARCHAR(50) NULL COMMENT '说明文字',
  `status` tinyint NOT NULL DEFAULT 0 COMMENT '状态，0-可用，1-不可用',
  `createtime` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `modifytime` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后更新时间',
  `createby` varchar(50) NULL COMMENT '创建者',
  `modifyby` varchar(50) NULL COMMENT '最后更新者',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


DROP TABLE IF EXISTS `sys_config`;
CREATE TABLE `sys_config` (
  `name` varchar(64) NOT NULL COMMENT '配置名',
  `value` text,
  `descr` varchar(256) NOT NULL COMMENT '描述说明',
  PRIMARY KEY (`name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4


DROP TABLE IF EXISTS `user_vcode`;
CREATE TABLE `user_vcode` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `phone` varchar(32) NOT NULL COMMENT '手机号码',
  `vcode` varchar(32) NOT NULL COMMENT '验证码',
  `category` tinyint(4) DEFAULT NULL COMMENT '类型，1：注册，2：忘记密码',
  `verify_time` datetime DEFAULT NULL COMMENT '验证时间',
  `status` int(11) DEFAULT '1' COMMENT '状态，1为已验证',
  `ip` varchar(32) DEFAULT NULL COMMENT 'ip地址',
  `create_time` datetime NOT NULL,
  `modify_time` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `app` varchar(32) DEFAULT NULL,
  `times` tinyint(4) DEFAULT '1',
  `mac` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `phone` (`phone`),
  KEY `app_category` (`category`,`app`),
  KEY `mac` (`mac`)
) ENGINE=InnoDB AUTO_INCREMENT=8 DEFAULT CHARSET=utf8 COMMENT='用户验证码'


DROP TABLE IF EXISTS `sms_log`;
CREATE TABLE `sms_log` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `phone` varchar(16) NOT NULL COMMENT '手机号码',
  `gateway` varchar(32) NOT NULL COMMENT '发送网关',
  `content` varchar(256) NOT NULL COMMENT '短信内容',
  `length` smallint(6) NOT NULL COMMENT '短信长度',
  `status` varchar(32) DEFAULT '1' COMMENT '发送状态，由短信网关返回',
  `create_time` datetime NOT NULL,
  `modify_time` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `ip` varchar(32) DEFAULT NULL COMMENT 'ip地址',
  `app` varchar(32) DEFAULT NULL COMMENT '来源应用',
  `scene` varchar(32) DEFAULT NULL COMMENT '应用场景',
  PRIMARY KEY (`id`),
  KEY `phone` (`phone`),
  KEY `gateway` (`gateway`),
  KEY `app_scene` (`app`,`scene`)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8 COMMENT='短信记录'


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
